### ISSUE TITLE
PDBbind

### ISSUE THREAD

**Issue by amrhamedp** [zetayue/MXMNet#1]
Hello,
In the paper, pdbind is mentioned in the examples. I am not sure where can I find the benchmark in this repo. It is interesting to see how the non-bonded interactions between the ligand and the protein are treated.

**Comment by zetayue** [comment]
Hi,
Thank you for your interest! 

We use the PDBBind version which is included in the MoleculeNet benchmark: http://deepchem.io.s3-website-us-west-1.amazonaws.com/datasets/pdbbind_v2015.tar.gz

For the interactions in protein-ligand complexes, we don't consider the chemical bond information here and instead use distance cutoff to create the edges in molecular graphs. For the local interactions, we use a distance cutoff = 2Å. For the global (both local and non-local) interactions, we use a distance cutoff = 6Å. Note that we exclude the protein residues that are more than 6Å from the ligand, so that this setting can capture enough interactions.

More detail about the experiments on PDBBind can be found in the Appendix in https://arxiv.org/abs/2011.07457
