### ISSUE TITLE
No masking for one-hop angles

### ISSUE THREAD

**Issue by PiotrKaszuba** [zetayue/MXMNet#11]
Hi! Is it intended that one-hop angles are not masked similarly to two-hop angles? If so, could you explain why?

https://github.com/zetayue/MXMNet/blob/2205f6cdf9c6c9793a02839e1a31b1f21d37ebd5/model.py#L59-L81

I would imagine it could look like this:

```
mask = idx_i_2 != idx_j2
idx_i_2, idx_j1, idx_j2 = idx_i_2[mask], idx_j1[mask], idx_j2[mask]

idx_ji_2 = adj_t_col.storage.row()[mask]
idx_jj = adj_t_col.storage.value()[mask]
```

**Comment by PiotrKaszuba** [comment]
I believe that such masking would remove only trivial angles, ie. A-B-A, which are present in one-hop indices

**Comment by zetayue** [comment]
> Is it intended that one-hop angles are not masked similarly to two-hop angles? If so, could you explain why?

Yes, this considers a corner case for molecules like `A-B`. If the one-hop angles are masked, then there would be no message passing between A and B in `A-B` when doing local message passing.

Empirically, we find that removing the self-loops (just like the example code you suggested to add mask) actually doesn't affect the performance on QM9, since the corner case is rare.

**Comment by PiotrKaszuba** [comment]
I see. Indeed, the performance does not change when the self-loops are removed. Thank you!
