### ISSUE TITLE
Local cutoff distance

### ISSUE THREAD

**Issue by jangerit** [zetayue/MXMNet#5]
Hello!

Thank you for providing the code. 

I wonder what the default values for the local message passing are. The local cutoff distance is based on the distance between two atoms that share a bond, isn't it? It seems you updated some default parameters that influence the local message passing from 3.6179 to 5 a couple of weeks ago. Isn't now the denominator for the local cutoff distance == global cutoff distance, when using the default value for global cutoff distance of 5?

Thanks a lot for your help in advance!

**Comment by zetayue** [comment]
Hi! 

The parameter=5 you mentioned as shown below is used in the calculation of RBF and SBF functions in the local layer. The parameter should be equal to the largest edge length defined by `edge_index_l` to enable meaningful calculations.
https://github.com/zetayue/MXMNet/blob/fa1dbc5153d48b7380c9f20da21390e2a5aee8e5/model.py#L28-L30
Currently, the edges in the local layer `edge_index_l` are the chemical bonds processed by rdkit, so that the mentioned parameter should be equal to the longest bond, which depends on the dataset. 

Empirically, I didn't find the parameter affects the performance much: The edges with different lengths in each layer (local or global) can all be differently embedded in the corresponding layer for aggregation. So that I just use 5 for simplicity and 5Å is larger than any bond length.

**Comment by jangerit** [comment]
Thank you very much for the detailed explanation. It helped a lot.
