### ISSUE TITLE
Using torch geometric QM9 dataset with this repository

### ISSUE THREAD

**Issue by ekosman** [zetayue/MXMNet#6]
Hello

I'm trying to run this code using the torch geometric data source for QM9.

However, I encounter the following error in the `forward` function of `MXMNet`:

```
h = torch.index_select(self.embeddings, 0, x.long())
RuntimeError: Index is supposed to be an empty tensor or a vector
```

`x` is a `Tensor` of shape `556,11` that seem to contain integers.

**Comment by zetayue** [comment]
Hi!

`x` should have a shape of `N` that only stores the atom type indices of `N` atoms. So that `torch.index_select` can use those indices to select the corresponding atom embeddings. 

When using the `QM9` class in our `qm9_dataset.py`, `x` is computed as below to have a shape of `N`:
https://github.com/zetayue/MXMNet/blob/fa1dbc5153d48b7380c9f20da21390e2a5aee8e5/qm9_dataset.py#L228
You can double-check whether your data is loaded using the same approach.

**Comment by ekosman** [comment]
Hello, thank you very much!

Are these the atomic numbers? If so, the PyG dataset contains those in the `z` attribute. I've already tried to use this and it works fine, but I just want to make sure that I'm doing the right thing.

Moreover, why `self.embeddings` contains only 5 rows? Do you assume there are only 5 atomic numbers?

**Comment by zetayue** [comment]
> Are these the atomic numbers? If so, the PyG dataset contains those in the `z` attribute. I've already tried to use this and it works fine, but I just want to make sure that I'm doing the right thing.

Yes, these are just atomic numbers (integer values). 

> Moreover, why `self.embeddings` contains only 5 rows? Do you assume there are only 5 atomic numbers?

I'm using 5 because there are only 5 different types (H, C, N, O, F) in QM9. If you are using other datasets, be sure to use a larger value.

**Comment by ekosman** [comment]
Thank you very much
