### ISSUE TITLE
QM9 dataset's difference to pytorch-geometric version 

### ISSUE THREAD

**Issue by LingxiaoShawn** [zetayue/MXMNet#8]
Dear authors,
May I ask what is the difference between your qm9 dataset and pytorch geometric qm9 dataset? It seems that your come is coming from pytorch-geometric but maybe has some revision. Could please let me know the difference? Thank you!

**Comment by zetayue** [comment]
The main difference is that the QM9 dataset in PyG provides more features (like edge attributes, name, index) than we need in our QM9 dataset, so that we ignore the unused features to be fed into the dataloader. Also for node attributes (x in data), we here only use atom type instead of using more chemical features (atomic_number, aromatic, sp, sp2, sp3, num_hs) in PyG version.

Another difference is that in the QM9 dataset in PyG, when rdkit is uninstalled, the rdkit-processed data will be downloaded automatically. In our QM9 dataset, we remove that option and require to use rdkit to process the raw data to get features.

**Comment by LingxiaoShawn** [comment]
Thank you for the detailed explanation! If I'm correct, the current simplified QM9 is widely used by other baselines such as DimeNet  right?

**Comment by zetayue** [comment]
Yes, this is a common approach. However, we didn't test whether using more chemical features will improve the performance.
